name: CI/CD

on:
  push:
    branches: [ develop ] # production
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Copy .env
        run: cp .env.test .env

      - name: Install app
        run: composer install

      - name: Test PHP Stan
        run: ./vendor/bin/phpstan analyse

      - name: Test PHP Unit
        run: ./vendor/bin/phpunit
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         token: ${{ secrets.PUSH_TOKEN }}
  #     - name: Set up Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '16'
  #     - run: npm install
  #     - run: npm run production
  #     - name: Commit built assets
  #       run: |
  #         git config --local user.email "vpduy84@gmail.com"
  #         git config --local user.name "Duy Vo"
  #         git checkout -B deploy
  #         git add -f public/
  #         git commit -m "Build front-end assets"
  #         git push -f origin deploy
  #     - name: Deploy to Production
  #       uses: appleboy/ssh-action@master
  #       with:
  #         username: YOUR_USER_NAME
  #         host: YOUR_HOSTNAME
  #         password: ${{ secrets.SSH_PASSWORD}}
  #         script: 'cd /var/www/html/trangdo.one && ./server_deploy.sh'